(function(){
var l=this||self;function m(){}function n(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}var p="closure_uid_"+(1E9*Math.random()>>>0),aa=0;function ba(a,b,c){return a.call.apply(a.bind,arguments)}function ca(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,d);return a.apply(b,f)}}return function(){return a.apply(b,arguments)}}
function q(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?q=ba:q=ca;return q.apply(null,arguments)}function r(a,b){var c=a.split("."),d=l;c[0]in d||"undefined"==typeof d.execScript||d.execScript("var "+c[0]);for(var f;c.length&&(f=c.shift());)c.length||void 0===b?d[f]&&d[f]!==Object.prototype[f]?d=d[f]:d=d[f]={}:d[f]=b}
function t(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.N=function(d,f,e){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[f].apply(d,g)}};var u=null;function da(){return(new Date).getTime()}function ea(){return Date.now()}"undefined"===typeof Date.now?u=ea:u=da;function fa(a){this.l=void 0===a?16:a;16==this.l?(this.s=268435456,this.j=4026531839):(this.s=78364164096,this.j=2742745743359)}function v(a){return(Math.floor(Math.random()*a.j)+a.s).toString(a.l)};function w(a){this.j=a}w.prototype.supported=function(){return void 0!=window.localStorage};w.prototype.get=function(){return window.localStorage.getItem(this.j)};w.prototype.set=function(a){return window.localStorage.setItem(this.j,a)};w.prototype.set=w.prototype.set;var x=0;
function ha(){var a=navigator.userAgent,b=navigator.vendor,c=navigator.platform,d=navigator.appVersion;ia=[{h:a,i:" OPR/",o:" OPR",g:"Opera"},{h:a,i:" OPT/",o:" OPT",g:"Opera Touch"},{h:a,i:"Opera Mini",o:"Opera Mini",g:"Opera Mini"},{h:a,i:"Edge/",o:"Edge",g:"Edge"},{h:a,i:"Edg/",o:"Edg",g:"Edge"},{h:a,i:"EdgA/",o:"EdgA",g:"Edge"},{h:a,i:"EdgiOS/",o:"EdgiOS",g:"Edge"},{h:a,i:"YaBrowser",o:"YaBrowser",g:"Yandex"},{h:a,i:"SamsungBrowser",g:"SamsungBrowser"},{h:a,i:"UCBrowser",g:"UCBrowser"},{h:a,i:"UCMobile",
g:"UCBrowser"},{h:a,i:"Puffin",g:"Puffin"},{h:a,i:"Chrome",g:"Chrome"},{h:a,i:"OmniWeb",o:"OmniWeb/",g:"OmniWeb"},{h:a,i:"FxiOS",g:"Firefox",o:"FxiOS"},{h:a,i:"CriOS",g:"Chrome",o:"CriOS"},{h:a,i:"XiaoMi/MiuiBrowser",g:"XiaoMi/MiuiBrowser",o:"XiaoMi/MiuiBrowser"},{h:b,i:"Apple",g:"Safari",o:"Version"},{K:window.opera,g:"Opera",o:"Version"},{h:b,i:"iCab",g:"iCab"},{h:b,i:"KDE",g:"Konqueror"},{h:a,i:"Firefox",g:"Firefox"},{h:b,i:"Camino",g:"Camino"},{h:a,i:"Netscape",g:"Netscape"},{h:a,i:"MSIE",g:"Explorer",
o:"MSIE"},{h:a,i:"IEMobile",g:"IEMobile",o:"IEMobile"},{h:a,i:"Trident",g:"Explorer",o:"rv"},{h:a,i:"Gecko",g:"Mozilla",o:"rv"},{h:a,i:"Mozilla",g:"Netscape",o:"Mozilla"}];ja=[{h:c,i:"Win",g:"Windows"},{h:c,i:"Mac",g:"Mac"},{h:a,i:"Windows Phone",g:"Windows Phone"},{h:a,i:"Android",g:"Android"},{h:a,i:"OpenBSD",g:"OpenBSD"},{h:a,i:"SunOS",g:"SunOS"},{h:c,i:"Linux arm",g:"Android"},{h:c,i:"Linux",g:"Linux"},{h:c,i:"BlackBerry",g:"BlackBerry"},{h:c,i:"iPhone",g:"iPhone/iPod"},{h:c,i:"iPad",g:"iPad"}];
ka=[{h:c,i:"Win",g:"Windows"},{h:c,i:"Mac",g:"Mac"},{h:c,i:"Linux arm",g:"Android"},{h:c,i:"Linux aarch",g:"Android"},{h:c,i:"Linux",g:"Linux"},{h:c,i:"BlackBerry",g:"BlackBerry"},{h:c,i:"iPhone",g:"iPhone"},{h:c,i:"iPad",g:"iPad"}];la=[{g:"Windows",D:[{m:"Windows 10",r:/(Windows 10.0|Windows NT 10.0)/},{m:"Windows 8.1",r:/(Windows 8.1|Windows NT 6.3)/},{m:"Windows 8",r:/(Windows 8|Windows NT 6.2)/},{m:"Windows 7",r:/(Windows 7|Windows NT 6.1)/},{m:"Windows Vista",r:/Windows NT 6.0/},{m:"Windows Server 2003",
r:/Windows NT 5.2/},{m:"Windows XP",r:/(Windows NT 5.1|Windows XP)/},{m:"Windows 2000",r:/(Windows NT 5.0|Windows 2000)/},{m:"Windows ME",r:/(Win 9x 4.90|Windows ME)/},{m:"Windows 98",r:/(Windows 98|Win98)/},{m:"Windows 95",r:/(Windows 95|Win95|Windows_95)/},{m:"Windows NT 4.0",r:/(Windows NT 4.0|WinNT4.0|WinNT|Windows NT)/},{m:"Windows CE",r:/Windows CE/},{m:"Windows 3.11",r:/Win16/}]},{g:"Mac",D:[{m:"Mac OS X",r:/Mac OS X/},{m:"Mac OS",r:/(MacPPC|MacIntel|Mac_PowerPC|Macintosh)/}]},{g:"Windows Phone",
D:[{m:"Windows Phone 6.0",r:/Windows Phone 6.0/},{m:"Windows Phone 7.0",r:/Windows Phone 7.0/},{m:"Windows Phone 8.0",r:/Windows Phone 8.0/},{m:"Windows Phone 8.1",r:/Windows Phone 8.1/},{m:"Windows Phone 10.0",r:/Windows Phone 10.0/}]}];y="undefined"!==typeof window.orientation;A=B(ka)||"unknown";ma=na()||"unknown";C=B(ia)||"unknown";D=oa(a)||oa(d)||"unknown";E=B(ja)||"unknown";a:{var f=la,e=E;c=C;var g=D;b=e;for(var h=0;h<f.length;h++)if(f[h].g===e){for(e=0;e<f[h].D.length;e++){var k=f[h].D[e];
if(k.r.test(a)){b=k.m;if(/Windows/.test(b)){"Windows 10"===b&&(pa()&&(b="Windows 11"),x=1,qa());break a}break}}break}switch(b){case "Mac OS X":b=null;d=/(Mac OS X 10[\._\d]+)/.exec(a);null!==d&&1<=d.length&&(b=d[1]);"undefined"!==typeof navigator.platform&&null!==navigator.platform&&"MacIntel"===navigator.platform&&"undefined"!==typeof navigator.maxTouchPoints&&null!==navigator.maxTouchPoints&&5===navigator.maxTouchPoints&&("undefined"!==typeof navigator.hardwareConcurrency&&8===navigator.hardwareConcurrency&&
"undefined"===typeof navigator.mediaDevices?b="VisionOS":"undefined"!==typeof"".split&&null!=="".split&&4===b.split(" ").length&&(g=/(Version\/[\.\d]+)/.exec(a),null!==g&&1<g.length&&(a=g[1],null!==a&&1<a.length&&(a=a.split("/"),null!==a&&1<a.length&&(b="iPad X "+a[1])))));break;case "Android":b=null;a=/[^-](Android[^\d]?[\._\d]+)/.exec(a);null!==a&&1<=a.length&&(b=a[1]);"Chrome"===c&&110<=g&&(x=1,qa());break;case "iPad":case "iPhone":case "iPhone/iPod":b=null;a=/OS (\d+)_(\d+)_?(\d+)?/.exec(d);null!==
a&&(b="iOS "+(1<=a.length?a[1]:"unknown")+"."+(2<=a.length?a[2]:"unknown")+"."+(3<=a.length?a[3]|0:"0"));break;default:b=null}}F=b||E;b=C;"Chrome"===b&&"Brave"===ma&&(b="Brave");C=b;!0===y&&"Mac"===A&&(E=A="iPhone/iPad",b=(a="string"===typeof F&&null!==F)&&-1!==F.indexOf("iPad X"),(a=a&&-1!==F.indexOf("VisionOS"))&&(A="VisionOS"),b||a||(F=E))}function B(a){for(var b=0;b<a.length;++b){var c=a[b].h,d=a[b].K;G=a[b].o||a[b].g;if(c){if(-1!==c.indexOf(a[b].i))return a[b].g}else if(d)return a[b].g}}
function oa(a){var b=C;if(!b)return null;var c;switch(b){case "Safari":a=/\WVersion[^\d]([\.\d]+)/.exec(a);null!==a&&1<=a.length&&(c=a[1]);break;case "UCBrowser":-1===a.indexOf(G)&&(G="UCMobile");case "Opera":if("OPR"===G){a=/\WOPR[^\d]*([\.\d]+)/.exec(a);null!==a&&1<=a.length&&(c=a[1]);break}default:b=a.indexOf(G),-1!==b&&(c=a.substring(b+G.length+1))}return c?parseFloat(c):null}
function H(a){var b=null;try{b=new Worker(a)}catch(c){return null!==b&&"undefined"!==typeof b.terminate&&b.terminate(),-1!==c.toString().indexOf("is not a valid URL")}return!1}
function na(){var a=y,b=A;try{var c="undefined"!==typeof window.s&&"undefined"!==typeof window.s.M||"object"===typeof window.opera||"undefined"!==typeof window.s&&"object"===typeof window.s;if(c)return"Opera";if(c="undefined"!==typeof InstallTrigger)return"Firefox";if((c=/constructor/i.test(window.HTMLElement)||"[object SafariRemoteNotification]"===(!window.safari||"undefined"!==typeof safari&&safari.P).toString())||(c="undefined"!==typeof window.I))return"Safari";if(c=/*@cc_on!@*/false || (typeof document.documentMode !== "undefined"))return"Explorer";
if(!c&&"undefined"!==typeof window.G)return"Edge";if(H("brave://"))return"Brave";if(H("edge://"))return"Edge";if(H("puffin://"))return"Puffin";if(c="undefined"!==typeof window.j&&"undefined"==typeof window.v&&("undefined"!==typeof window.j.S||"undefined"!==typeof window.j.R||"undefined"!==typeof window.j.O))return"Chrome";if(a){if(c="undefined"!==typeof window.j&&"undefined"!==typeof window.j.L)return"SamsungBrowser";if(c="undefined"!==typeof window.J)return"UCBrowser"}if("iPhone"===b||"iPad"===b){if("undefined"!==
typeof navigator.serviceWorker)return"Safari";if("undefined"!==typeof window.F)return"Chrome"}if(c="undefined"!==typeof window.j&&"undefined"!==typeof window.v)return"Yandex"}catch(d){}return null}function I(a){return"undefined"!==typeof a&&null!==a}
function qa(){if("Firefox"===C||"Safari"===C)x=4;else if(!(1<x)&&(x=2,"undefined"!==typeof UAHintHighCollector&&I(navigator.userAgentData)&&I(navigator.userAgentData.getHighEntropyValues))){var a=navigator.userAgentData.getHighEntropyValues(["platformVersion"]);I(a)&&I(a.then)&&a.then(function(b){function c(d){return"undefined"!==typeof d&&null!==d}c(navigator.userAgentData.platform)&&"Windows"===navigator.userAgentData.platform?c(b)&&c(b.platformVersion)&&c(b.platformVersion.split)&&(b=parseInt(b.platformVersion.split(".")[0],
10),13<=b?(F="Windows 11",x=3):0<b?(F="Windows 10",x=3):x=4):c(navigator.userAgentData.platform)&&"Android"===navigator.userAgentData.platform&&c(b)&&c(b.platformVersion)&&c(b.platformVersion.split)&&(b=parseInt(b.platformVersion.split(".")[0],10),0<b?(F="Android "+b,x=3):x=4)})}}function pa(){if("Firefox"===C||"Safari"===C)return!1;try{if(I(document.fonts)&&I(document.fonts.check))return document.fonts.check("18px Segoe Fluent Icons")}catch(a){}return!1}
var ia={},ja={},ka={},la={},y,A,ma,C,D,E,F,G;var ra=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};var sa=Object.freeze||function(a){return a};function ta(){0!=ua&&(Object.prototype.hasOwnProperty.call(this,p)&&this[p]||(this[p]=++aa))}var ua=0;function J(a,b){this.type=a;this.j=this.target=b;this.defaultPrevented=!1}J.prototype.l=function(){this.defaultPrevented=!0};var va=function(){if(!l.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{l.addEventListener("test",m,b),l.removeEventListener("test",m,b)}catch(c){}return a}();var K;a:{var wa=l.navigator;if(wa){var xa=wa.userAgent;if(xa){K=xa;break a}}K=""};var ya="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function za(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var e=0;e<ya.length;e++)c=ya[e],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function L(a){L[" "](a);return a}L[" "]=m;var Aa=-1!=K.indexOf("Gecko")&&!(-1!=K.toLowerCase().indexOf("webkit")&&-1==K.indexOf("Edge"))&&!(-1!=K.indexOf("Trident")||-1!=K.indexOf("MSIE"))&&-1==K.indexOf("Edge");function M(a,b){J.call(this,a?a.type:"");this.relatedTarget=this.j=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.s=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.j=b;var f=a.relatedTarget;if(f){if(Aa){a:{try{L(f.nodeName);var e=!0;break a}catch(g){}e=
!1}e||(f=null)}}else"mouseover"==c?f=a.fromElement:"mouseout"==c&&(f=a.toElement);this.relatedTarget=f;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=
a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType="string"===typeof a.pointerType?a.pointerType:Ba[a.pointerType]||"";this.state=a.state;this.s=a;a.defaultPrevented&&M.H.l.call(this)}}t(M,J);var Ba=sa({2:"touch",3:"pen",4:"mouse"});M.prototype.l=function(){M.H.l.call(this);var a=this.s;a.preventDefault?a.preventDefault():a.returnValue=!1};var N="closure_listenable_"+(1E6*Math.random()|0);var Ca=0;function Da(a,b,c,d,f){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.C=f;this.key=++Ca;this.A=this.B=!1}function O(a){a.A=!0;a.listener=null;a.proxy=null;a.src=null;a.C=null};function P(a){this.src=a;this.j={};this.l=0}P.prototype.add=function(a,b,c,d,f){var e=a.toString();a=this.j[e];a||(a=this.j[e]=[],this.l++);var g=Q(a,b,d,f);-1<g?(b=a[g],c||(b.B=!1)):(b=new Da(b,this.src,e,!!d,f),b.B=c,a.push(b));return b};function R(a,b){var c=b.type;if(c in a.j){var d=a.j[c],f=ra(d,b),e;(e=0<=f)&&Array.prototype.splice.call(d,f,1);e&&(O(b),0==a.j[c].length&&(delete a.j[c],a.l--))}}
function Q(a,b,c,d){for(var f=0;f<a.length;++f){var e=a[f];if(!e.A&&e.listener==b&&e.capture==!!c&&e.C==d)return f}return-1};var S="closure_lm_"+(1E6*Math.random()|0),T={},Ea=0;function U(a,b,c,d,f){if(d&&d.once)Fa(a,b,c,d,f);else if(Array.isArray(b))for(var e=0;e<b.length;e++)U(a,b[e],c,d,f);else c=V(c),a&&a[N]?a.l.add(String(b),c,!1,n(d)?!!d.capture:!!d,f):Ga(a,b,c,!1,d,f)}
function Ga(a,b,c,d,f,e){if(!b)throw Error("Invalid event type");var g=n(f)?!!f.capture:!!f,h=Ha(a);h||(a[S]=h=new P(a));c=h.add(b,c,d,g,e);if(!c.proxy){d=Ia();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)va||(f=g),void 0===f&&(f=!1),a.addEventListener(b.toString(),d,f);else if(a.attachEvent)a.attachEvent(Ja(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Ea++}}
function Ia(){function a(c){return b.call(a.src,a.listener,c)}var b=Ka;return a}function Fa(a,b,c,d,f){if(Array.isArray(b))for(var e=0;e<b.length;e++)Fa(a,b[e],c,d,f);else c=V(c),a&&a[N]?a.l.add(String(b),c,!0,n(d)?!!d.capture:!!d,f):Ga(a,b,c,!0,d,f)}
function La(a,b,c,d,f){if(Array.isArray(b))for(var e=0;e<b.length;e++)La(a,b[e],c,d,f);else(d=n(d)?!!d.capture:!!d,c=V(c),a&&a[N])?(a=a.l,b=String(b).toString(),b in a.j&&(e=a.j[b],c=Q(e,c,d,f),-1<c&&(O(e[c]),Array.prototype.splice.call(e,c,1),0==e.length&&(delete a.j[b],a.l--)))):a&&(a=Ha(a))&&(b=a.j[b.toString()],a=-1,b&&(a=Q(b,c,d,f)),(c=-1<a?b[a]:null)&&Ma(c))}
function Ma(a){if("number"!==typeof a&&a&&!a.A){var b=a.src;if(b&&b[N])R(b.l,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Ja(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Ea--;(c=Ha(b))?(R(c,a),0==c.l&&(c.src=null,b[S]=null)):O(a)}}}function Ja(a){return a in T?T[a]:T[a]="on"+a}function Ka(a,b){if(a.A)var c=!0;else{c=new M(b,this);var d=a.listener,f=a.C||a.src;a.B&&Ma(a);c=d.call(f,c)}return c}
function Ha(a){a=a[S];return a instanceof P?a:null}var Na="__closure_events_fn_"+(1E9*Math.random()>>>0);function V(a){if("function"===typeof a)return a;a[Na]||(a[Na]=function(b){return a.handleEvent(b)});return a[Na]};function W(){ta.call(this);this.l=new P(this);this.I=this}t(W,ta);W.prototype[N]=!0;W.prototype.removeEventListener=function(a,b,c,d){La(this,a,b,c,d)};function Oa(a,b,c,d){if(b=a.l.j[String(b)]){b=b.concat();for(var f=!0,e=0;e<b.length;++e){var g=b[e];if(g&&!g.A&&g.capture==c){var h=g.listener,k=g.C||g.src;g.B&&R(a.l,g);f=!1!==h.call(k,d)&&f}}}};function X(a,b){W.call(this);this.v=a||1;this.u=b||l;this.F=q(this.J,this);this.G=Date.now()}t(X,W);X.prototype.s=!1;X.prototype.j=null;
X.prototype.J=function(){if(this.s){var a=Date.now()-this.G;if(0<a&&a<.8*this.v)this.j=this.u.setTimeout(this.F,this.v-a);else{this.j&&(this.u.clearTimeout(this.j),this.j=null);var b=this.I;a="tick";var c=a.type||a;if("string"===typeof a)a=new J(a,b);else if(a instanceof J)a.target=a.target||b;else{var d=a;a=new J(c,b);za(a,d)}b=a.j=b;Oa(b,c,!0,a);Oa(b,c,!1,a);this.s&&(Pa(this),this.start())}}};X.prototype.start=function(){this.s=!0;this.j||(this.j=this.u.setTimeout(this.F,this.v),this.G=Date.now())};
function Pa(a){a.s=!1;a.j&&(a.u.clearTimeout(a.j),a.j=null)};var Qa={};function Ra(a,b,c,d,f){var e=new fa(36),g=Math.floor(Math.random()*e.j),h=Math.floor(Math.random()*e.j);h=(h-h%256+6+g)%e.j;var k=(885187064159+g)%e.j;g=v(e)+(g+e.s).toString(e.l);h=(k+e.s).toString(e.l)+(h+e.s).toString(e.l);a="https://"+a+"/"+g+b;c=[h+"="+c,v(e)+v(e)+"="+d];"undefined"!==typeof f&&null!==f&&0<f.length&&c.push(v(e)+v(e)+"="+f);return a+="?"+c.join("&")}function Sa(){var a=u(),b=new fa(16);b=v(b)+v(b)+v(b)+v(b);return[0,0,a,a,b].join(":")}
function Ta(){var a=new w("ed73f20edbf2b73");if(!a.supported())return null;a=a.get();if(null===a)return null;var b=a.split("_");2===b.length&&(a=b[0]);return"0:"+a}function Ua(){var a=Ta();if(null===a)if(a=new w("ed73f20edbf2b74"),a.supported()){var b=a.get();null===b&&(b=Sa());var c=a.set;var d=b.split(":");if(5!=d.length)d=b;else{var f=parseInt(d[1],10)+1,e=parseInt(d[2],10),g=u();g>e+157788E5?d=Sa():(d[1]=f.toString(),d[3]=g,d=d.join(":"))}c.call(a,d);a="1:"+b}else a=null;return a}
function Va(a,b){var c={iceServers:[{urls:"turn:aa.online-metrix.net?transport=tcp",username:a,credential:b},{urls:"turn:aa.online-metrix.net?transport=udp",username:a,credential:b}]};return"undefined"!==typeof window.RTCPeerConnection&&null!==window.RTCPeerConnection?new window.RTCPeerConnection(c):"undefined"!==typeof window.webkitRTCPeerConnection&&null!==window.webkitRTCPeerConnection?new window.webkitRTCPeerConnection(c):"undefined"!==typeof window.u&&null!==window.u?new window.u(c):null}
function Wa(a){var b=/^[01]:[a-z0-9:]+$/;return 2<=a.length&&b.test(a)}function Xa(a){var b=/^[a-zA-Z0-9_\-/]+$/;return 128>=a.length&&b.test(a)}function Ya(a){var b=/^[a-z0-9]+$/;return 8>=a.length&&b.test(a)}
function Za(a,b){if(Ya(a)&&Xa(b)){"undefined"!==typeof navigator&&ha();var c=C,d=D,f=Ua();if(Wa(f))try{var e=Va("3:"+a+":"+b+":"+c+":"+d+":"+f,b);if(e&&"undefined"!==typeof e.createDataChannel&&null!==e.createDataChannel){e.createDataChannel(Math.random().toString());var g=function(){};c=function(h){e.setLocalDescription(h,g,g)};"undefined"===typeof Promise||0<e.createOffer.length?e.createOffer(c,g):e.createOffer().then(c,g);setInterval(function(){"undefined"!==typeof e.close&&null!==e.close&&e.close();
"undefined"!==typeof e.onicecandidate&&null!==e.onicecandidate&&(e.onicecandidate=function(){},e=null)},1E4)}}catch(h){}}}
function $a(a,b,c,d,f,e){a._l=function(g){return function(){"undefined"===typeof g.readyState&&(g.readyState="complete");b&&(g.domain=b);try{var h=g.createElement("script");h.type="text/javascript";h.text='var tmx_document_referrer = "'+encodeURIComponent(document.referrer.substring(0,255))+'";';ab(h);g.body.appendChild(h);g.tmx_dr_in=1}catch(z){}try{g.getElementsByTagName("html")[0].setAttribute("lang","en")}catch(z){}h=Ra(c,".js",d,f,e);var k=g.createElement("script");k.setAttribute("src",h);ab(k);
g.body.appendChild(k)}}(a)}function bb(a){"undefined"!==typeof a._l&&a._l()}
function Y(a,b,c,d,f){f=void 0===f?0:f;if(!Qa[b]){Qa[b]=!0;var e=document.createElement("iframe");e.setAttribute("src","about:blank");ab(e);e.id="tmx_tags_iframe_"+b;e.title="empty";"undefined"!==typeof e.tabIndex&&(e.tabIndex="-1");e.setAttribute("aria-disabled","true");e.setAttribute("aria-hidden","true");e.setAttribute("data-time",u());(e.frameElement||e).style.cssText="width: 0px; height: 0px; border: 0; position: absolute; top: -5000px;";var g=document.getElementById("thm_iframe_loc"),h=null;
g?g.parentNode.insertBefore(e,g):document.body.appendChild(e);g=null;try{g=e.contentWindow.document}catch(z){h=document.domain;e.setAttribute("src","javascript:var d=document.open();d.domain='"+h+"';void(0);");try{g=e.contentWindow.document}catch(gb){a=Ra(a,".htm",b,c,d);e.setAttribute("src",a);return}}var k=g.open();$a(k,h,a,b,c,d);if(2===f)U(e,"load",function(){},!0,null),k.close(),bb(k);else{try{U(e,"load",function(){bb(k)},!0,null)}catch(z){k.write('<html lang="en"><body onload="document._l();"></body></html>')}k.close()}}}
var Z=null;function ab(a){null!==Z&&(a.setAttribute("nonce",Z),a.getAttribute("nonce")!==Z&&(a.nonce=Z))}function cb(a){for(var b;null!==(b=document.getElementById(a));)b.parentElement.removeChild(b)}function db(){return"undefined"!==typeof document.body&&null!==document.body}function eb(a,b,c,d,f){var e=new X(10);U(e,"tick",function(){db()&&(Y(a,b,c,d,f),Pa(e))});e.start()}
function fb(a,b,c,d,f){Za(b,c);Qa[b]=!1;var e="WebkitAppearance"in document.documentElement.style;if(1===f||2===f)eb(a,b,c,d,f);else if(!db()||"complete"!==document.readyState&&e){var g="undefined"!==typeof window?window:document.body;try{U(g,"load",function(){Y(a,b,c,d)},!0,null)}catch(k){var h=g.onload;g.onload=function(){var z=!0;null!==h&&"function"===typeof h&&(z=h());setTimeout(function(){Y(a,b,c,d)},200);g.onload=h;return z}}}else Y(a,b,c,d,f)}r("threatmetrix.load_method.WAIT_FOR_ONLOAD",0);
r("threatmetrix.load_method.RUN_IMMEDIATE",1);r("threatmetrix.load_method.RUN_IMMEDIATE_IFRAME",2);
r("threatmetrix.profile",function(a,b,c,d,f,e){f=void 0===f?0:f;e=void 0===e?null:e;if("undefined"!==typeof a&&"undefined"!==typeof b&&"undefined"!==typeof c&&8===b.length){if(-1!==c.indexOf(":"))throw Error("invalid session_id "+c);cb("tmx_tags_iframe_"+b);cb("tdz_ifrm_"+b);cb("tmx_tag_"+b);if("undefined"!==typeof e&&null!==e)Z=e;else if(e=document,"undefined"!==typeof e.currentScript&&null!==e.currentScript){var g=e.currentScript.getAttribute("nonce");"undefined"!==typeof g&&null!==g&&""!==g?Z=
g:"undefined"!==typeof e.currentScript.nonce&&null!==e.currentScript.nonce&&""!==e.currentScript.nonce&&(Z=e.currentScript.nonce)}fb(a,b,c,d,f)}});}).call(this);
